using UnityEngine;
using Cinemachine;

public class CursorManager : MonoBehaviour
{

    public CinemachineVirtualCamera mainGameplayCam;
    public CinemachineBrain brain;
    private static CursorManager _instance;
    

    void Start()
    {
        brain = Camera.main.GetComponent<CinemachineBrain>();
        mainGameplayCam.Priority = 100; // fuerza que esta sea la primera
        ForceCursorUpdate();
    }

    void Update()
    {
        ForceCursorUpdate();
    }
    void ForceCursorUpdate()
    {
        if (mainGameplayCam == null || brain == null)
        {
            Debug.LogWarning("Main Gameplay Camera or Cinemachine Brain is not assigned.");
            return;
        }

        ICinemachineCamera activeICam = brain.ActiveVirtualCamera;

        if (activeICam == null)
        {
            Debug.Log("No active virtual camera.");
            return;
        }

        // Si es una StateDrivenCamera, accedemos a su c√°mara activa real
        if (activeICam is CinemachineStateDrivenCamera stateCam)
        {
            var child = stateCam.LiveChild as CinemachineVirtualCamera;

            if (child != null && child == mainGameplayCam)
            {
                LockCursor(true);
            }
            else
            {
                LockCursor(false);
            }
        }
        else if (activeICam is CinemachineVirtualCamera virtualCam)
        {
            if (virtualCam == mainGameplayCam)
            {
                LockCursor(true);
            }
            else
            {
                LockCursor(false);
            }
        }
        else
        {
            Debug.LogWarning("Active camera is not a CinemachineVirtualCamera or CinemachineStateDrivenCamera.");
            LockCursor(false);
        }
    }
    public void LockCursor(bool lockCursor)
    {
        if (lockCursor)
        {
            Cursor.lockState = CursorLockMode.Locked;
            Cursor.visible = false;
        }
        else
        {
            Cursor.visible = true;
            Cursor.lockState = CursorLockMode.None;
        }
    }
}